---
title: "DLM Dashboard Usage"
date: "Generated on: `r Sys.Date()`"
output: html_document
---

```{r, echo=FALSE}
library(reshape2)
library(ggplot2)
usage.wide = read.csv(file.path("..", "usage-reports-email-account","usage-email-account.csv"))
usage.long = melt(usage.wide, id.vars=c("Period.ending.on"))
usage.long$"Period.ending.on" <- as.Date(usage.wide$"Period.ending.on","%Y-%m-%d")
```

```{r, echo=FALSE,fig.width=9, fig.height=7}
axes <- c("Total.teams.in.last.30.days", "Engaged.teams.in.last.30.days")#, "New.teams.in.last.30.days")
subdata1 <- subset(usage.long, variable %in% axes[1])
subdata2 <- subset(usage.long, variable %in% axes[2])
subdata3 <- subset(usage.long, variable %in% axes[3])
subdata <- rbind(subdata1,subdata2,subdata3)
labeldata <- rbind(tail(subdata1, n=1),tail(subdata2, n=1),tail(subdata3, n=1))


fudge_factor <- 0
p <- ggplot(subdata, aes(Period.ending.on, value+fudge_factor, color = variable, group = variable))
p + geom_point() + geom_line() + geom_text(data = labeldata,  aes(Period.ending.on, value+fudge_factor, label = value+fudge_factor, vjust = 3)) + xlab("Period Ending On") + ylab("Teams")

```
